
import java.awt.Dimension;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */

/**
 *
 * @author David
 */
public class frmMenus extends javax.swing.JFrame {
private EntityManagerFactory emf;
    /**
     * Creates new form frmMenus
     */
    public frmMenus() {
        initComponents();
        this.setTitle("Sistema de Tienda ABC");
        setTitle("Menú Principal");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Establecer el tamaño máximo
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuarchivo = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        menualmacen = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        menucategorias = new javax.swing.JMenuItem();
        menucompras = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        menuventas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuconsultas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuconfiguraciones = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        menuarchivo.setMnemonic('f');
        menuarchivo.setText("Archivo");

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Cerrar sesion");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        menuarchivo.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Salir");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        menuarchivo.add(saveAsMenuItem);

        menuBar.add(menuarchivo);

        menualmacen.setMnemonic('e');
        menualmacen.setText("Almacen");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Productos");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        menualmacen.add(cutMenuItem);

        menucategorias.setMnemonic('y');
        menucategorias.setText("Categorias");
        menucategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucategoriasActionPerformed(evt);
            }
        });
        menualmacen.add(menucategorias);

        menuBar.add(menualmacen);

        menucompras.setMnemonic('h');
        menucompras.setText("Compras");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Compras");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        menucompras.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Proveedores");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        menucompras.add(aboutMenuItem);

        menuBar.add(menucompras);

        menuventas.setText("Ventas");

        jMenuItem1.setText("Ventas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuventas.add(jMenuItem1);

        jMenuItem2.setText("Clientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuventas.add(jMenuItem2);

        menuBar.add(menuventas);

        menuconsultas.setText("Consultas");

        jMenuItem3.setText("Ventas realizadas");
        menuconsultas.add(jMenuItem3);

        jMenuItem4.setText("Compras Realizadas");
        menuconsultas.add(jMenuItem4);

        menuBar.add(menuconsultas);

        menuconfiguraciones.setText("Configuraciones");

        jMenuItem5.setText("Configuracion de usuarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuconfiguraciones.add(jMenuItem5);

        jMenuItem6.setText("Empleados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuconfiguraciones.add(jMenuItem6);

        menuBar.add(menuconfiguraciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
                                                 
    // Cerrar el JFrame actual (el menú principal)
    this.dispose(); // Esto cerrará la ventana actual

    // Crear una nueva instancia de frmlogin
    frmlogin loginForm = new frmlogin();
    loginForm.setVisible(true); // Hacer visible el formulario de inicio de sesión

    // Si quieres que el formulario de inicio de sesión esté centrado en la pantalla
    loginForm.setLocationRelativeTo(null);


    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
                                               
    this.dispose(); // Cierra el JInternalFrame actual


    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
      // Crear una instancia de EntityManagerFactory
EntityManagerFactory emf = Persistence.createEntityManagerFactory("CapaLogica_ventas_jar_1.0-SNAPSHOTPU");

// Crear una nueva instancia de frmproveedores con el EntityManagerFactory
frmproveedores proveedoresForm = new frmproveedores(emf);

// Añadir el internal frame al panel contenedor
contenedor.add(proveedoresForm);

// Hacer visible el internal frame
proveedoresForm.setVisible(true);



    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
     
                                         
    // Crear una instancia de EntityManagerFactory
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("CapaLogica_ventas_jar_1.0-SNAPSHOTPU");
    
    // Crear una nueva instancia de frmproducto con el EntityManagerFactory
    frmproducto productoForm = new frmproducto(emf);
    
    // Añadir el internal frame al panel contenedor
    contenedor.add(productoForm);
    
    // Hacer visible el internal frame
    productoForm.setVisible(true);
    
    // Centrar el formulario en el contenedor
   





        
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void menucategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucategoriasActionPerformed
     // Crear una instancia de EntityManagerFactory
EntityManagerFactory emf = Persistence.createEntityManagerFactory("CapaLogica_ventas_jar_1.0-SNAPSHOTPU");

// Crear una nueva instancia de frmcategoria con el EntityManagerFactory
frmcategoria categoriaForm = new frmcategoria(emf);

// Añadir el internal frame al panel contenedor
contenedor.add(categoriaForm);

// Hacer visible el internal frame
categoriaForm.setVisible(true);

// Centrar el formulario en el contenedor
categoriaForm.setLocation((contenedor.getWidth() - categoriaForm.getWidth()) / 2, 
                           (contenedor.getHeight() - categoriaForm.getHeight()) / 2);

    }//GEN-LAST:event_menucategoriasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    // Crear una instancia de EntityManagerFactory
EntityManagerFactory emf = Persistence.createEntityManagerFactory("CapaLogica_ventas_jar_1.0-SNAPSHOTPU");

// Crear una nueva instancia de frmcliente con el EntityManagerFactory
frmcliente clienteForm = new frmcliente(emf);

// Añadir el internal frame al panel contenedor
contenedor.add(clienteForm);

// Hacer visible el internal frame
clienteForm.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
  // Crear una nueva instancia de frmusuarios
frmusuarios usuariosForm = new frmusuarios(); // No se pasa el EntityManagerFactory

// Añadir el internal frame al panel contenedor
contenedor.add(usuariosForm);

// Hacer visible el internal frame
usuariosForm.setVisible(true);



    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     // Crear una instancia de EntityManagerFactory
EntityManagerFactory emf = Persistence.createEntityManagerFactory("CapaLogica_ventas_jar_1.0-SNAPSHOTPU");

// Crear una nueva instancia de frmEmpleados con el EntityManagerFactory
frmempleados empleadosForm = new frmempleados(emf);

// Añadir el internal frame al panel contenedor
contenedor.add(empleadosForm);

// Hacer visible el internal frame
empleadosForm.setVisible(true);


    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 // Crear una instancia de EntityManagerFactory
EntityManagerFactory emf = Persistence.createEntityManagerFactory("CapaLogica_ventas_jar_1.0-SNAPSHOTPU");

// Crear una nueva instancia de frmventa con el EntityManagerFactory
frmventa ventaForm = new frmventa(emf);

// Añadir el internal frame al panel contenedor
contenedor.add(ventaForm);

// Hacer visible el internal frame
ventaForm.setVisible(true);



    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
 // Crear una nueva instancia de frmcompra
frmcompra compraForm = new frmcompra();

// Añadir el internal frame al panel contenedor
contenedor.add(compraForm);

// Hacer visible el internal frame
compraForm.setVisible(true);

    }//GEN-LAST:event_contentsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menualmacen;
    private javax.swing.JMenu menuarchivo;
    private javax.swing.JMenuItem menucategorias;
    private javax.swing.JMenu menucompras;
    private javax.swing.JMenu menuconfiguraciones;
    private javax.swing.JMenu menuconsultas;
    private javax.swing.JMenu menuventas;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
